name: PlayerAI
main: net.nuggetmc.ai.PlayerAI
version: 3.0-BETA
api-version: 1.16
author: HorseNuggets

permissions:
  playerai.*:
    description: PlayerAI parent permission.
    default: op
    children:
      playerai.manage: true
  playerai.manage:
    description: Allows for PlayerAI bot management.
    default: op