name: PlayerAI
main: net.nuggetmc.ai.PlayerAI
version: 1.0
api-version: 1.16
author: HorseNuggets
commands:
  playerai:
    description: The PlayerAI base command.
    permission: playerai.manage
    usage: /playerai
    aliases: [bot, pai, ai]
permissions:
  playerai.*:
    description: PlayerAI parent permission.
    default: op
    children:
      playerai.manage: true
  playerai.manage:
    description: Allows for PlayerAI NPC management.
    default: op